#!/usr/bin/env python -B

from __future__ import print_function
from __future__ import unicode_literals

import json
import subprocess
import sys


def execute(cmd, pipe=None):
    p = subprocess.Popen(cmd,
                         stdin=subprocess.PIPE,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE)
    return p.communicate(pipe)


def revision():
    out, err = execute('arc branch --output json'.split())
    for b in json.loads(out).values():
        if b['current']:
            return int(b['revision'])


def query(revision):
    q = {'revisionIDs': [revision]}
    out, err = execute('arc call-conduit differential.querydiffs'.split(), pipe=json.dumps(q))
    j = json.loads(out)
    return max(j['response'].keys())


if __name__ == '__main__':
    r = revision()
    print(query(r))
