#!/bin/sh -e

LOCAL="${HOME}/apportable/github/${1}.git"
if [ -z "${2}" ]
then
    REPO="${1}"
else
    REPO="${2}"
fi
REMOTE="git@github.com:apportable/${1}.git"

git clone --local "${LOCAL}" "${REPO}"
cd "${REPO}"
git remote rm origin
git remote add origin "${REMOTE}"
git fetch
git branch --set-upstream-to=origin/$(git rev-parse --abbrev-ref HEAD)
