#!/bin/sh

REPO=$1
TOOLCHAIN=toolchain/macosx

if [ -z $REPO ]
then
    echo Usage: $(basename $0) '<name-of-dcf-clone>'
    exit 1
fi

cd ~/apportable/repos

clone dcf $@

cd $REPO
git submodule update --init --recursive
ln -sv ~/code/scripts/dcf.mk Makefile
pushd .git/info
rm -f exclude
ln -sv ../../../dcf/.git/info/exclude
popd

mkdir -p $TOOLCHAIN
pushd $TOOLCHAIN
ln -sv ../../../dcf/$TOOLCHAIN/cache
popd
