#!/bin/sh

function index() {
    defaults $1 com.apple.dt.Xcode IDEIndexDisable $2
}

case $1 in
    on)
        index delete > /dev/null 2> /dev/null
        exit 0
        ;;
    off)
        index write 1
        exit 0
        ;;
    status)
        if (index read > /dev/null 2> /dev/null)
        then
            echo Indexing off
        else
            echo Indexing on
        fi
        exit 0
        ;;
    *)
        echo Usage: $(basename $0) '{on,off,status}'
        exit 1
        ;;
esac